# Generated by Django 6.1.1 on 2026-09-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('nr_inwentarzowy', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(max_length=100)),
                ('dostepnosc', models.BooleanField(default=True)),
                ('is_wycofany', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(auto_now_add=True)),
                ('planowana_data_zwrotu', models.DateField()),
                ('data_zwrotu', models.DateField(blank=True, null=True)),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wypozyczenia', to='sprzet.sprzet')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wypozyczenia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
