# Generated by Django 6.1.1 on 2026-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(max_length=100)),
                ('dostępność', models.BooleanField(default=True)),
            ],
        ),
    ]
