# Generated by Django 6.1.1 on 2026-09-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprzet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprzet',
            old_name='dostępność',
            new_name='dostepnosc',
        ),
    ]
